apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: movie-web
stringData:
  CLIENT_ID: ""
  CLIENT_SECRET: ""
  REDIRECT_URI: ""
  REFRESH_TOKEN: ""
  ADMIN_MAIL: ""
  MONGO_URL: ""
  SECRET_KEY: ""
  KAFKA_GROUP: "movie-web"
  KAFKA_TOPIC: "mail-services"

