apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modsecurity-data-pvc
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage