apiVersion: v1
kind: ConfigMap
metadata:
  name: modsecurity-config
  namespace: ingress-nginx
data:
  modsecurity.conf: |
    SecRuleEngine On                
    SecRequestBodyAccess On         
    SecResponseBodyAccess On        
    SecAuditLog /dev/stdout
    SecDebugLog /dev/stderr 
    SecDefaultAction "phase:1,deny,log,status:403"
    SecDefaultAction "phase:2,deny,log,status:403"
    SecAuditLogFormat JSON
    SecAuditEngine RelevantOnly
    SecAuditLogParts ABCEFHZ
    SecRequestBodyLimitAction Reject
    SecCollectionTimeout 3600
    SecAuditLogRelevantStatus "^(?:5|4(?!04))"
    SecDebugLogLevel 3 