apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: block-pkg-mgmt-tools-exec
spec:
  message: "Alert! unauthorized apt process in kubernetes namespace test"
  severity: 8
  selector:
    matchExpressions:
      - key: namespace
        operator: In
        values:
          - default
  process:
    matchPaths:
      - path: /usr/bin/apt-get
      - path: /usr/bin/apt
      - path: /usr/bin/nc
      - path:
  action: Block