apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-deployment
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
    spec:
      containers:
        - name: {{ .Values.global.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: {{ .Values.service.protocol }}
              name: {{ .Values.service.protocolName }}
          resources:
            {{- if or .Values.resources.limits.cpu .Values.resources.limits.memory }}
            limits:
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.resources.limits.memory }}
              memory: {{ .Values.resources.limits.memory }}
              {{- end }}
            {{- end }}
            {{- if or .Values.resources.requests.cpu .Values.resources.requests.memory }}
            requests:
              {{- if .Values.resources.requests.cpu }}
              cpu: {{ .Values.resources.requests.cpu }}
              {{- end }}
              {{- if .Values.resources.requests.memory }}
              memory: {{ .Values.resources.requests.memory }}
              {{- end }}
            {{- end }}
          {{- if .Values.global.enableComponents.configmap }}
          volumeMounts:
            - name: configmap-volume
              mountPath: /home/node/app/.env
              subPath: .env
          {{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      dnsPolicy: ClusterFirst
      {{- if .Values.global.enableComponents.configmap }}
      volumes:
        - name: configmap-volume
          configMap:
            defaultMode: 420
            name: {{ .Values.global.appName }}-configmap
      {{- end }}
