apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: controller-manager-access-file-blocked
spec:
  message: "Alert! Access to Controller Manager files has been blocked" 
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: k8s-master
  file:
    severity: 5
    matchPaths:
    - path: /etc/kubernetes/controller-manager.conf
      readOnly: false
      ownerOnly: true
    matchDirectories:
    - dir: /etc/kubernetes/manifests/
      readOnly: false
      ownerOnly: true
    - dir: /etc/kubernetes/secrets/
      readOnly: false
      ownerOnly: true
    - dir: /etc/kubernetes/pki/
      readOnly: false
      ownerOnly: true
    action: Block