apiVersion: apps/v1
kind: Deployment
metadata:
  name: bill-service-v1
  namespace: movie-web
  labels:
    app: bill-service
    version: v1
spec:
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: bill-service
      version: v1
  template:
    metadata:
      labels:
        app: bill-service
        version: v1
    spec:
      serviceAccountName: movie-web-backend
      containers:
        - name: bill-service
          image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-bill-service:v2_0c382c3a
          ports:
            - containerPort: 3003
              protocol: TCP  
          resources:
            requests:
              memory: "256Mi"
          env:
            - name: USER_SERVER_HOST
              value: k8s-user-service
            - name: USER_SERVER_PORT
              value: "3001"
          envFrom:
            - secretRef:
                name: bill-service-secret
      imagePullSecrets:
        - name: auth-registry
