apiVersion: v1
kind: Secret
metadata:
  name: bill-service-secret
  namespace: movie-web
stringData:
  MONGO_URL: ""
  SECRET_KEY: ""
  KEY_1: ""
  KEY_2: ""
  APP_ID: "2554"
  APP_URL: "https://movieclient.netlify.app"
