apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-pvc
  namespace: wazuh
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
