apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/elasticsearch
    server: 192.168.80.230
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
