apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-2204-deployment
  labels:
    app: ubuntu
    version: "22.04"
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
        version: "22.04"
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:22.04
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80