apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedReposv2
metadata:
  name: allowed-images-rule
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps", "extensions"]
        kinds: ["Deployment", "ReplicaSet", "DaemonSet", "StatefulSet"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["test", "movie-web-blue-green"]
  parameters:
    allowedImages:
      - "docker.io/*"
      - "dev.nhatanhdevops.website/onlineshop:*" 
      - "registry.nhatanhmovieweb.website/*"
      - "service.istio.io/*"
      - "istio/proxyv2"
      - "istio/proxyv2:*"
  validationFailureAction: enforce