apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: allowed-repository-rule
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps", "extensions"]
        kinds: ["Deployment", "ReplicaSet", "DaemonSet", "StatefulSet"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["test", "movie-web-blue-green"]
  parameters:
    repos:
      - "docker.io/"
      - "dev.nhatanhdevops.website/onlineshop"
      - "ubuntu"
      - "registry.nhatanhmovieweb.website"
      - "service.istio.io/*"
      - "proxyv2"
  validationFailureAction: enforce