apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAutomountServiceAccountTokenPod
metadata:
  name: block-automount-service-account-token
  annotations:
    description: "Prevents Pods from automatically mounting Service Account Tokens"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps", "extensions"]
        kinds: ["Deployment", "ReplicaSet", "DaemonSet", "StatefulSet"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "kube-public"]
    excludedNamespaces:
      - "kube-system"
      - "kube-public"
      - "gatekeeper-system"
  parameters:
  enforcementAction: deny