apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoUpdateServiceAccount
metadata:
  name: block-serviceaccount-update
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment", "ReplicaSet", "DaemonSet", "StatefulSet"]
      - apiGroups: ["batch"]
        kinds: ["Job", "CronJob"]
      - apiGroups: [""]
        kinds: ["ReplicationController"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: [ "test", "movie-web-blue-green"]
  parameters:
    allowedUsers: 
      - "system:serviceaccount:kube-system:generic-garbage-collector"
      - "cluster-admin"
    allowedGroups:
      - "system:masters"
      - "k8s-admins"
  enforcementAction: deny