apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-web-frontend 
  namespace: movie-web
  labels:
    app: movie-web-frontend 
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: movie-web-frontend 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: movie-web-frontend 
    spec:
      containers:
        - name: movie-web-frontend 
          image: registry.nhatanhmovieweb.website/onlineshop/movie-web-frontend-production:v53_6ca38318
          ports:
            - containerPort: 80
              protocol: TCP  
              name: tcp
          resources:
            requests:
              memory: "256Mi"
          env:
            - name: REACT_APP_GATEWAY_HOST
              value: "k8s-api-gateway"
            - name: REACT_APP_GATEWAY_PORT
              value: "8800"
          envFrom:
            - secretRef:
                name: movie-web-frontend-secret
      imagePullSecrets:
        - name: auth-registry
      dnsPolicy: ClusterFirst
      restartPolicy: Always

