apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-autoscale-v1
  namespace: movie-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service-v1  
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
