apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-v1
  namespace: movie-web
  labels:
    app: user-service
    version: v1
spec:
  revisionHistoryLimit: 10 
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: v1
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      serviceAccountName: movie-web-backend
      containers:
        - name: user-service
          image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-user-service:v5_14382fd0
          ports:
            - containerPort: 3001
              protocol: TCP  
          resources:
            requests:
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: user-service-secret
          env:
            - name: MOVIE_SERVER_HOST
              value: k8s-movie-service
            - name: MOVIE_SERVER_PORT
              value: "3002"
            - name: KAFKA_HOST
              value: "3.26.189.155"
            - name: KAFKA_PORT
              value: "9094"
      imagePullSecrets:
        - name: auth-registry
