apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: movie-web
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-user-service:v4_4657257d
          ports:
            - containerPort: 3001
              protocol: TCP  
          resources:
            requests:
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: user-service-secret
          env:
            - name: MOVIE_SERVER_HOST
              value: k8s-movie-service
            - name: MOVIE_SERVER_PORT
              value: "3002"
            - name: KAFKA_HOST
              value: "192.168.80.230"
            - name: KAFKA_PORT
              value: "9094"
      imagePullSecrets:
        - name: auth-registry