apiVersion: v1
kind: ConfigMap
metadata:
  name: bill-service-configmap
  namespace: movie-web
data:
  .env: |
    MONGO_URL=
    SECRET_KEY=
    KEY_1=
    KEY_2=
    APP_ID=2554
    APP_URL=https://movieclient.netlify.app
    USER_SERVER_HOST=k8s-user-service
    USER_SERVER_PORT=3001
