apiVersion: v1
kind: Service
metadata:
  name: movie-web-backend-bill-service
  namespace: movie-web
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: bill-service
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP  
      name: tcp
  type: ClusterIP
  sessionAffinity: None
