apiVersion: v1
kind: Service
metadata:
  name: movie-web-backend-movie-service
  namespace: movie-web
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: movie-service
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP  
      name: tcp
  type: ClusterIP
  sessionAffinity: None
