input {
  file {
    path => "/var/log/snort/alert.log"
    start_position => "beginning"
  }
}

filter {
  if [path] =~ "access" {
    mutate { replace => { "type" => "snort-logs" } }
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}

output {
  elasticsearch {
    hosts => ["https://elastic.nhatanhmovie.website:443"]
    user => "elastic"
    password => "unHM80KHtSMHv9dZ"
    index => "snort-elasticsearch-%{+YYYY.MM.dd}"
    action => "create"
    data_stream => false
  }
  stdout { codec => rubydebug }
}