apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma-pv
  labels:
    app: uptime-kuma
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /data/uptime-kuma
    server: 192.168.1.114
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage