apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: load-balancer-autoscale
  namespace: movie-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50