apiVersion: v1
kind: ServiceAccount
metadata:
  name: clean-service-non-endpoints
  namespace: movie-web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clean-service-non-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: clean-service-non-endpoints
    namespace: movie-web