apiVersion: v1
kind: Service
metadata:
  name: blocked-external-ips-service
  namespace: movie-web
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: user-service
  externalIPs:
    - 171.239.11.44
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP  
      name: tcp
