apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: movie-web-frontend-rolebinding
  namespace: movie-web
subjects:
- kind: ServiceAccount
  name: movie-web-frontend
  namespace: movie-web
roleRef:
  kind: Role
  name: movie-web-frontend-role
  apiGroup: rbac.authorization.k8s.io