apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-autoscale-v2
  namespace: movie-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-v2  
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50