apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: warning-create-account-create-local-account
spec:
  nodeSelector: 
    matchExpressions:
      kubernetes.io/hostname: k8s-worker-1
  message: "Notification! User and password added/modified"
  file:
    severity: 3
    matchPaths:
    - path: /etc/passwd
    - path: /etc/shadow
    action: Block
  process:
    severity: 3
    matchPaths:
    - path: /bin/useradd
    - path: /bin/adduser
    action: Block