apiVersion: apps/v1
kind: Deployment
metadata:
  name: automount-service-deployment
  namespace: test
  labels:
    app: automount-service
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: automount-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: automount-service
    spec:
      automountServiceAccountToken: true
      containers:
        - name: automount-service
          image: redis:7.0-alpine  
          ports:
            - containerPort: 3002
              protocol: TCP
              name: tcp
          resources:
            requests:
              memory: "256Mi"
          volumeMounts:
            - name: service-account-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
      volumes:
        - name: service-account-token
          secret:
            secretName: default-token  
      dnsPolicy: ClusterFirst
      restartPolicy: Always