apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: movie-web
data: 
  .env: |
    CLIENT_ID=""
    CLIENT_SECRET=""
    REDIRECT_URI="https://developers.google.com/oauthplayground"
    REFRESH_TOKEN=""
    ADMIN_MAIL="alonhuan123@gmail.com"
    MONGO_URL=""
    SECRET_KEY="happynewyear"
    KAFKA_GROUP="movie-web"
    KAFKA_TOPIC="mail-services"
    MOVIE_SERVER_HOST="movie-web-backend-movie-service"
    MOVIE_SERVER_PORT="3002"
    KAFKA_HOST="171.235.188.237"
    KAFKA_PORT="9094"
