apiVersion: v1
data:
  accounts.dev: login
  accounts.devops: login
  accounts.leader: login
  accounts.nhatanh2709: login
  url: https://argocd.example.com
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cm","namespace":"argocd"}}
  creationTimestamp: "2025-03-09T08:58:24Z"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  resourceVersion: "327023"
  uid: 4d33e0e1-0ea6-4204-990f-396c49be7e51
root@k8s-master:/tools/argocd# kubectl get configmap argocd-notifications-cm -n argocd -o yaml
apiVersion: v1
data:
  service.webhook.app-sync-body-info: |
    url: https://argo-notifications.nhatanhmovieweb.shop
    headers:
    - name: argocd-notification
      value: argocd-notification-value
    - name: Content-Type
      value: application/json
  template.app-sync-body-info: |
    webhook:
      app-sync-body-info:
        method: POST
        path: /webhook/argocd
        body: |
          {
            "app": "{{.app.metadata.name}}",
            "namespace": "{{.app.metadata.namespace}}",
            "status": "{{.app.status.sync.status}}",
            "health": "{{.app.status.health.status}}",
            "repo": "{{.app.spec.source.repoURL}}",
            "revision": "{{.app.spec.source.targetRevision}}",
            "message": "Application sync status changed"
          }
  trigger.on-sync-succeeded: |
    - when: app.status.sync.status == 'Synced'
      send: [app-sync-body-info]
  trigger.on-sync-started: |
    - when: app.status.operationState.phase == 'Running'
      send: [app-sync-body-info]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-cm","namespace":"argocd"}}
  creationTimestamp: "2025-10-25T13:58:00Z"
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-notifications-cm
  namespace: argocd
  resourceVersion: "3140035"
  uid: 7dacff8a-847d-4384-aad3-421587e24dc3