apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-web-backend-bill-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/movie-web-manifest/movie-web-backend-bill-service.git'
    targetRevision: main
    path: ./
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true