apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bill-service-autoscale-v2
  namespace: movie-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bill-service-v2
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
