apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: movie-service-autoscale-v2  
  namespace: movie-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-service-v2  
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
