apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-v1
  namespace: movie-web
  labels:
    app: movie-service
    version: v1
spec:
  revisionHistoryLimit: 10  
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
      version: v1
  template:
    metadata:
      labels:
        app: movie-service
        version: v1
    spec:
      serviceAccountName: movie-web-backend
      containers:
        - name: movie-service
          image: dev.nhatanhdevops.website/onlineshop/movie-web-backend-movie-service:v4_a8c76ee2
          ports:
            - containerPort: 3002
              protocol: TCP  
          resources:
            requests:
              memory: "256Mi"
          env:
            - name: USER_SERVER_HOST
              value: k8s-user-service
            - name: USER_SERVER_PORT
              value: "3001"
            - name: ELASTIC_SEARCH_HOST
              value: elasticsearch
            - name: ELASTIC_SEARCH_PORT
              value: "9200"
          envFrom:
            - secretRef:
                name: movie-service-secret
      imagePullSecrets:
        - name: auth-registry
