apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: movie-web
  name: movie-web-frontend-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]