apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-container-raw-sockets
  namespace: insecure
spec:
  message: "Alert! Block raw sockets in container"
  serverity: 1
  selector:
    matchLabels:
      app: nginx
      app: ubuntu
      app: network-tools
  capabilities:
    matchCapabilities:
    - capability: net_raw
  action: 
    Block