apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-container-raw-sockets
  namespace: default
spec:
  message: "Alert! Block raw sockets in container"
  severity: 1
  capabilities:
    matchCapabilities:
    - capability: net_raw
  action: 
    Block