apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-template-deployment
  namespace: ingress-nginx
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
        ports:
        - containerPort: 22
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"  
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-template-deployment
  namespace: ingress-nginx
  labels:
    app: ubuntu
  namspace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        command: ["/bin/bash"]
        args: ["-c", "apt-get update -y && apt-get install iputils nmap nmap-ncat net-tools tcpdump dsniff -y && sleep infinity"]
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi" 
