apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-template-deployment
  namespace: test
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
        ports:
        - containerPort: 22
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"  
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-tools-deployment
  labels:
    app: network-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tools
  template:
    metadata:
      labels:
        app: network-tools
    spec:
      containers:
      - name: network-tools-container
        image: alpine:latest  # Sử dụng Alpine Linux
        command: ["/bin/sh", "-c"]
        args:
          - apk update && 
            apk add --no-cache iputils nmap nmap-ncat net-tools tcpdump bind-tools busybox-extras && 
            sleep infinity
        securityContext:
          privileged: true  # Cần thiết cho một số công cụ như nmap
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"