driver:
  enabled: true
  kind: ebpf 
  ebpf:
    hostNetwork: true
    leastPrivileged: true


controller:
  kind: daemonset
collectors:
  kubernetes:
    enabled: true
  containerd:
    enabled: true
    socket: /var/run/containerd/containerd.sock

falcosidekick:
  enabled: true
  webui:
    enabled: true
    redis:
      persistence:
        enabled: true
        storageClass: "nfs-storage"
        size: 2Gi
  config:
    slack:
      webhookurl: "https://hooks.slack.com/services/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"
      channel: "devops"
      footer: "https://github.com/falcosecurity/falcosidekick"
      username: "nhatanh2709"
      outputformat: "all"
      minimumpriority: "error"
      messageformat: 'Alert : rule *{{ .Rule }}* triggered '
    elasticsearch:
      hostport: "https://elastic.nhatanhmovie.website"
      index: "falco"
      type: "_doc"
      suffix: "daily"
      username: "elastic"
      password: "OT8SKk2XgKAbfjsT"
      minimumpriority: "notice"
      maxconcurrentrequests: 1
      mutualtls: false
      checkcert: true
      mapping: 
        "@timestamp": "date"
        "rule": "text"
        "output": "text"
        "priority": "keyword"
        "time": "date"

falco:
  jsonOutput: true
  httpOutput:
    enabled: true
    url: http://falco-falcosidekick:2801




auditLog:
  enabled: true