driver:
  enabled: true
  kind: ebpf 
  ebpf:
    hostNetwork: true
    leastPrivileged: true

controller:
  kind: daemonset
collectors:
  kubernetes:
    enabled: true
  containerd:
    enabled: true
    socket: /var/run/containerd/containerd.sock


falcosidekick:
  enabled: true
  webui:
    enabled: true
    redis:
      host: "falco-falcosidekick-ui-redis" 
      port: 6379
      persistence:
        enabled: true
        storageClass: "nfs-storage"
        size: 2Gi


falco:
  privileged: true
  hostPID: true
  hostNetwork: true
  jsonOutput: true
  httpOutput:
    enabled: true
    url: http://falco-falcosidekick:2801




auditLog:
  enabled: true