apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-service-configmap
  namespace: movie-web
data:
  .env: |
    MONGO_URL="mongodb+srv://anh:27092004@backenddb.2qdkr.mongodb.net/netflix?retryWrites=true&w=majority&appName=BackendDB"
    SECRET_KEY="happynewyear"
    USER_SERVER_HOST="movie-web-backend-user-service"
    USER_SERVER_PORT="3001"
    ELASTIC_SEARCH_HOST="elasticsearch-master.logging.svc.cluster.local"
    ELASTIC_SEARCH_PORT="9200"
    ELASTIC_SEARCH_USERNAME=elastic
    ELASTIC_SEARCH_PASSWORD=9713DF6Zd5v4Gd6E

