apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-0
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/elasticsearch-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch-1
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/elasticsearch-1
